CimKara/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ensachage.urls')),
    path('', include('Users.urls')),
]

Users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views


app_name = 'users'

urlpatterns = [
    path('login/', login_views, name="logIn"),
    path('logup/', logup_views, name='logup'),
    path('logout/', logout_views, name='logOut'),
    # path('logup/userCreate/', logup_user_create_views, name="createUser"),
    
    path('reset_password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', views.PasswordResetDoneView.as_view(), name='reset_password_send'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='reset_password_confirm'),
    path('reset_password_complete/', views.PasswordResetCompleteView.as_view(), name='reset_password_complete'),
    
]

Users/models.py
from django.db import models

# Create your models here.

Users/views.py
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
# Create your views here.


def login_views(request):
    error=False
    message=""
    if request.method == "POST":
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        
        user = User.objects.filter(username=username).first()
        if user is not None:
            auth_user = authenticate(username=user.username, password=password)
        
            if auth_user :
                login(request, auth_user)
                return redirect('list')                
            else:
                message = ("l'utilisateur {} n'est pas authentifié").format(user.username)
        else:
            message = ("Ce nom d'utilisateur {} na pas de compte").format(username)
        
    return render(request, 'Users/login.html', {'message': message})


def logup_views(request):
    logup=False
    message=""
    if request.method == "POST":
        lastname = request.POST.get('lastname', None).upper()
        firstname = request.POST.get('firstname', None).capitalize()
        email = request.POST.get('email', None)
        password1 = request.POST.get('pwd1', None)
        password2 = request.POST.get('pwd2', None)
        username = firstname[0].upper()+lastname.lower()
        print(username)
            
        user = User.objects.filter(Q(username=username)|Q(email=email)).first()
        # print(user.username, user.email)
        
        if user is not None:
        
            if user.username == username:
                message="Cet nom d'utilisateur {} existe déjà!".format(username)
                
            if user.email == email:
                message="Cet email {} existe déjà!".format(email)
        else:
            if len(password1)<6:
                message = "Le mot de passe doit faire au moins 6 caractères!" 
            
            else:
                if password1!= password2:
                    message = "Les mots de passe ne correspondent pas!"
                    
                else:
                    user = User.objects.create_user(last_name=lastname,first_name=firstname,username=username, email=email)
                    user.set_password(password1)
                    if user:
                        logup=True
                        user.save()
                        message= "votre compte a été bien créé et votre nom d'utilisateur est: {}".format(username)
                        return render(request, 'Users/welcome.html', {'message': message, 'logup': logup})
                                    
    return render(request, 'Users/logup.html', {'message': message})


def logout_views(request):
    logout(request)
    return redirect('list')

# def logup_user_create_views(request):
#     return render(request, 'Users/welcome.html', {})

templates/Users/login.html
{% extends 'base.html' %}

{% block title %}
  Login
{% endblock %}

{% block content %}
  <div class="container mt-3">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.min.css" rel="stylesheet" />
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4 bg-dark rounded-3">
        <div>
          {% if message %}
            <div class="alert alert-danger">
              <h5 class="h6 text-center mt-3">{{ message }}</h5>
            </div>
          {% endif %}
        </div>
        <!-- Pills navs -->
        <ul class="nav nav-pills nav-justified my-3" id="ex1" role="tablist">
          <li class="nav-item" role="presentation">
            <a class="nav-link active" id="tab-login" href="{% url 'users:logIn' %}" role="tab" aria-controls="pills-login" aria-selected="true">Login</a>
          </li>
          <li class="nav-item" role="presentation">
            <a class="nav-link" id="tab-register" href="" role="tab" aria-controls="pills-register" aria-selected="false">Register</a>
          </li>
        </ul>
        <!-- Pills navs -->

        <!-- Pills content -->
        <div class="tab-content">
          <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
            <form action="" method="post" novalidate>
              {% csrf_token %}
              <div class="text-center mb-3">
                <p>Sign in with:</p>
                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1"><i class="fab fa-facebook-f"></i></button>

                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1"><i class="fab fa-google"></i></button>

                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1"><i class="fab fa-twitter"></i></button>

                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1"><i class="fab fa-github"></i></button>
              </div>

              <p class="text-center">or:</p>

              <!-- Email input -->
              <div data-mdb-input-init class="form-outline mb-4">
                <input type="text" id="loginName" class="form-control" name="username" required />
                <label class="form-label" for="loginName">Username</label>
              </div>

              <!-- Password input -->
              <div data-mdb-input-init class="form-outline mb-4">
                <input type="password" id="loginPassword" class="form-control" name="password" required />
                <label class="form-label" for="loginPassword">Password</label>
              </div>

              <!-- 2 column grid layout -->
              <div class="row mb-4">
                <div class="col-md-6 d-flex justify-content-center">
                  <!-- Checkbox -->
                  <div class="form-check mb-3 mb-md-0">
                    <input class="form-check-input" type="checkbox" value="" id="loginCheck" checked />
                    <label class="form-check-label" for="loginCheck">Remember me</label>
                  </div>
                </div>

                <div class="col-md-6 d-flex justify-content-center">
                  <!-- Simple link -->
                  <a href="#!">Forgot password?</a>
                </div>
              </div>

              <!-- Submit button -->
              <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

              <!-- Register buttons -->
              <div class="text-center">
                <p>
                  Not a member? <a href="">Register</a>
                </p>
              </div>
            </form>
          </div>
          <div class="tab-pane fade" id="pills-register" role="tabpanel" aria-labelledby="tab-register">
            <form>
              <div class="text-center mb-3">
                <p>Sign up with:</p>
                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1"><i class="fab fa-facebook-f"></i></button>

                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1"><i class="fab fa-google"></i></button>

                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1"><i class="fab fa-twitter"></i></button>

                <button data-mdb-ripple-init type="button" class="btn btn-secondary btn-floating mx-1"><i class="fab fa-github"></i></button>
              </div>

              <p class="text-center">or:</p>

              <!-- Name input -->
              <div data-mdb-input-init class="form-outline mb-4">
                <input type="text" id="registerName" class="form-control" />
                <label class="form-label" for="registerName">Name</label>
              </div>

              <!-- Username input -->
              <div data-mdb-input-init class="form-outline mb-4">
                <input type="text" id="registerUsername" class="form-control" />
                <label class="form-label" for="registerUsername">Username</label>
              </div>

              <!-- Email input -->
              <div data-mdb-input-init class="form-outline mb-4">
                <input type="email" id="registerEmail" class="form-control" />
                <label class="form-label" for="registerEmail">Email</label>
              </div>

              <!-- Password input -->
              <div data-mdb-input-init class="form-outline mb-4">
                <input type="password" id="registerPassword" class="form-control" />
                <label class="form-label" for="registerPassword">Password</label>
              </div>

              <!-- Repeat Password input -->
              <div data-mdb-input-init class="form-outline mb-4">
                <input type="password" id="registerRepeatPassword" class="form-control" />
                <label class="form-label" for="registerRepeatPassword">Repeat password</label>
              </div>

              <!-- Checkbox -->
              <div class="form-check d-flex justify-content-center mb-4">
                <input class="form-check-input me-2" type="checkbox" value="" id="registerCheck" checked aria-describedby="registerCheckHelpText" />
                <label class="form-check-label" for="registerCheck">I have read and agree to the terms</label>
              </div>

              <!-- Submit button -->
              <button data-mdb-ripple-init type="submit" class="btn btn-primary btn-block mb-3">Sign in</button>
            </form>
          </div>
        </div>
        <!-- Pills content -->
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
{% endblock %}

templates/Users/logup.html
{% extends 'base.html' %}

{% block content %}
  {% if user.is_superuser %}
    <div class="container-fluid">
      <section class="pb-5">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.min.css" rel="stylesheet" />
        <div class="row">
          <div class="col-lg-4 col-sm-12 clo-md-4 mt-4"></div>
          <div class="col-lg-4 col-sm-12 clo-md-4 mt-4">
            <div class="card" style="background-color: #000000;">
              <div class="h4 card-header text-capitalize">
                <div class="row">
                  <div class="col-12 mt-3 mb-1">
                    <h5 class="h4 text-uppercase text-light">registration form</h5>
                  </div>
                </div>
              </div>
              <div class="card-body">
                {% if message %}
                  <h5 class="h6 text-center alert alert-danger"><span class="fst-italic">{{ message }}</span></h5>
                {% endif %}
                <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <!-- 2 column grid layout with text inputs for the first and last names -->
                  <div class="row mb-4">
                    <div class="col">
                      <div data-mdb-input-init class="form-outline">
                        <input type="text" id="form3Example1" class="form-control" name="lastname" value="" required />
                        <label class="form-label text-light" for="form3Example1">Nom:</label>
                      </div>
                    </div>
                    <div class="col">
                      <div data-mdb-input-init class="form-outline">
                        <input type="text" id="form3Example2" class="form-control" name="firstname" value="" required />
                        <label class="form-label text-light" for="form3Example2">Prénom:</label>
                      </div>
                    </div>
                  </div>
                  <div data-mdb-input-init class="form-outline mb-4">
                    <input type="email" id="form3Example4" class="form-control" name="email" required />
                    <label class="form-label text-light" for="form3Example4">Email:</label>
                  </div>
                  <div class="row mb-4">
                    <div class="col">
                      <div data-mdb-input-init class="form-outline">
                        <input type="password" id="form3Example2" class="form-control" name="pwd1" value="" required />
                        <label class="form-label text-light" for="form3Example2">Password:</label>
                      </div>
                    </div>
                    <div class="col">
                      <div data-mdb-input-init class="form-outline">
                        <input type="password" id="form3Example1" class="form-control" name="pwd2" value="" required />
                        <label class="form-label text-light" for="form3Example1">Confirm Password:</label>
                      </div>
                    </div>
                  </div>
                  <!-- Password input -->

                  <!-- Submit button -->
                  <button data-mdb-ripple-init type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
                </form>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-12 clo-md-4 mt-4"></div>
        </div>
      </section>
    </div>
  {% else %}
    <div class="container text-center">
      <div class="mt-5">
        <p class="alert alert-danger h3 fst-italic">Vous n'êtes pas autorisé à créer des compte. Veuillez-vous adresser votre responsable.</p>
      </div>
    </div>
  {% endif %}

  <!-- 

<div class="container h5 text-light text-center" style="font-family: 'EB Garamond', serif;">
    Bienvenus dans notre communauté; votre nom d'utilisateur et <span class="text-info">{{ user.username }}</span> a été bien ajouté
    Clique<a href="{% url 'users:logIn' %}"> ici </a>pour te connecter à ton compte
</div>  -->
{% endblock %}

templates/Users/welcome.html
{% extends 'home.html' %}


{% block content %}
<div class="container text-center">
    <h1 class="h4">bienvenus sur la page d'inscription</h1>
    
    {% if logup %}
    <div>
        
        {% if message %}
            <div class="alert alert-success">
                <p class="h4"><span class="text-decoration-underlin">{{ message }}</span> cliqué <a href="{% url 'users:logIn' %}">Ici</a> pour vous connecter</p>
            </div>
        {% endif %}
            
    </div>
    {% endif %}
        
</div>
{% endblock content %}
    